export { default as Navbar } from './Navbar/Navbar'
export { default as NavbarMobile } from './NavbarMobile/NavbarMobile'
export { default as Search } from './Search/Search'
export { default as Pagination } from './Pagination/Pagination'
export { default as ListGames } from './ListGames/ListGames'
export { default as Game } from './Game/Game'
export { default as OptionsFilter } from './OptionsFilter/OptionsFilter'
export { default as Dropdown } from './Dropdown/Dropdown'
export { default as Footer } from './Footer/Footer'
export { default as CampoForm } from './CampoForm/CampoForm'
export { default as ModalImage } from './ModalImage/ModalImage'
export { default as CampoFormOpts } from './CampoFormOpts/CampoFormOpts'
export { default as ModalSelectOpts } from './ModalSelectOpts/ModalSelectOpts'

export { default as NotFound } from './NotFound/NotFound'
export { default as LoadingGames } from './LoadingGames/LoadingGames'
export { default as LoadingDetail } from './LoadingDetail/LoadingDetail'
export { default as SpinnerLoading } from './SpinnerLoading/SpinnerLoading'
